@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class AnimatedTile {
  + AnimatedTile(int[], double): 
  + update(double): void
   baseId: int
   currentFrameId: int
}
class Animation {
  + Animation(BufferedImage[], double, boolean): 
  + reset(): void
  + update(double): void
   currentFrame: BufferedImage
   finished: boolean
}
class AnimationManager {
  + AnimationManager(): 
  + addAnimation(String, Animation): void
  + playAnimation(String): void
  + update(double): void
   current: Animation
}
class CollisionChecker {
  + CollisionChecker(GameModel): 
  - isCollision(int, int, int): boolean
  - checkAxisY(Entity, EntityBounds): void
  + checkTile(Entity): void
  - checkAxisX(Entity, EntityBounds): void
  + updateEntityLayer(Entity, EntityBounds, int, int): void
  - isOutOfBounds(int, int): boolean
}
class Entity {
  + Entity(): 
  # worldX: int
  # screenX: int
  # currentLayer: int
  # screenY: int
  # solidArea: Rectangle
  # direction: Direction
  # collisionX: boolean
  # dx: int
  # worldY: int
  # speed: int
  # dy: int
  # collisionY: boolean
  + move(): void
  + setScreenPosition(int, int): void
  + setWorldPosition(int, int): void
  + update(): void
   collisionX: boolean
   collisionY: boolean
   speed: int
   screenX: int
   currentLayer: int
   dx: int
   dy: int
   layer: int
   screenY: int
   direction: Direction
   worldY: int
   worldX: int
   solidArea: Rectangle
   collisionOn: boolean
}
class FrameTimeline {
  + FrameTimeline(int, double, boolean): 
  - currentFrame: int
  - finished: boolean
  + update(double): void
  + reset(): void
   currentFrame: int
   finished: boolean
}
class GameController {
  + GameController(GameModel, GameView): 
  + stopGame(): void
  + startGame(): void
  + update(double): void
  + render(): void
}
class GameLoop {
  + GameLoop(GameController): 
  + run(): void
  + stopGameLoop(): void
}
class GameMap {
  + GameMap(String, int, int, int, int): 
  + GameMap(String, int, int): 
  - maxMapCol: int
  - graphicLayerNum: int
  - maxMapRow: int
  - loadMap(String): void
  - loadCollisionLayer(String, int): void
  + setMapTile(int, int, int, int): void
  + getMapTile(int, int, int): int
  + hasCollision(int, int, int): boolean
   maxMapCol: int
   maxMapRow: int
   graphicLayerNum: int
}
class GameModel {
  + GameModel(): 
  - gameState: GameState
  - player: Player
  - debugMode: boolean
  - collisionChecker: CollisionChecker
  + update(KeyHandler, double): void
   gameState: GameState
   player: Player
   worldMap: GameMap
   collisionChecker: CollisionChecker
   debugMode: boolean
}
class GameObject {
  + GameObject(): 
}
class GameSetting {
  + GameSetting(): 
}
class GameView {
  + GameView(GameModel): 
  - playerRender: PlayerRender
  # paintComponent(Graphics): void
  + updateAnimations(double): void
   playerRender: PlayerRender
}
class KeyHandler {
  + KeyHandler(): 
  - debugToggle: boolean
  - pauseToggle: boolean
  - up: boolean
  - down: boolean
  - attack: boolean
  - right: boolean
  - left: boolean
  + keyReleased(KeyEvent): void
  + keyPressed(KeyEvent): void
  + keyTyped(KeyEvent): void
   pauseToggle: boolean
   debugToggle: boolean
   right: boolean
   down: boolean
   attack: boolean
   up: boolean
   left: boolean
}
class Main {
  + Main(): 
  + main(String[]): void
}
class MapLayer {
  + MapLayer(int, int, int, String): 
  - pathFile: String
  - level: int
  + getLayerTileId(int, int): int
  + setLayerTile(int, int, int): void
  + loadMapLayer(String): void
   level: int
   pathFile: String
}
class MapRender {
  + MapRender(): 
  + DrawMap(GameMap, TileSet, Player, Graphics2D): void
  ~ drawTile(int, int, int, TileSet, Player, Graphics2D): void
  + drawAllGameLayers(GameMap, Player, Graphics2D): void
  ~ drawLayer(int, GameMap, TileSet, Player, Graphics2D): void
}
class OBJ_Tree {
  + OBJ_Tree(): 
}
class Player {
  + Player(): 
  - state: PlayerState
  - updateState(KeyHandler, boolean): void
  + update(KeyHandler, double): void
  - updateMovement(KeyHandler, double): boolean
  - initializeDefaultValues(): void
  + stopAttack(): void
   state: PlayerState
   facingRight: int
}
class PlayerRender {
  + PlayerRender(): 
  - loadAnimations(): void
  + drawSolidArea(Graphics2D, Player): void
  + updateAnimations(Player, double): void
  + draw(Graphics2D, Player): void
}
class SpriteLoader {
  + SpriteLoader(): 
  + getAnimationFrames(BufferedImage, int, int, int, int, int): BufferedImage[]
  + loadSpriteSheet(String): BufferedImage
}
class TileRegion {
  + TileRegion(int, int, int): 
}
class TileSet {
  + TileSet(String, int, int, int): 
  - tileSetImg: BufferedImage
  + getTileIdToDraw(int): int
  + getTileY(int): int
  + getTileX(int): int
  + loadTileSet(int, int, int): void
  - loadAnimatedTiles(): void
  + updateAnimTile(double): void
   tileSetImg: BufferedImage
}
class UI {
  + UI(GameModel, PlayerRender, MapRender): 
  - drawPauseScreen(): void
  + draw(Graphics2D): void
  + getXforCenteredText(String): int
}

AnimatedTile     "1" *-[#595959,plain]-> "timeline\n1" FrameTimeline    
AnimatedTile      -[#595959,dashed]->  FrameTimeline    : "«create»"
Animation         -[#595959,dashed]->  FrameTimeline    : "«create»"
Animation        "1" *-[#595959,plain]-> "timeline\n1" FrameTimeline    
AnimationManager "1" *-[#595959,plain]-> "animations\n*" Animation        
CollisionChecker  -[#595959,dashed]->  Entity           
CollisionChecker  -[#595959,dashed]->  GameMap          
CollisionChecker "1" *-[#595959,plain]-> "gameModel\n1" GameModel        
Entity            -[#595959,dashed]->  GameSetting      
GameController    -[#595959,dashed]->  GameLoop         : "«create»"
GameController   "1" *-[#595959,plain]-> "loop\n1" GameLoop         
GameController   "1" *-[#595959,plain]-> "model\n1" GameModel        
GameController   "1" *-[#595959,plain]-> "view\n1" GameView         
GameController    -[#595959,dashed]->  KeyHandler       : "«create»"
GameController   "1" *-[#595959,plain]-> "keyHandler\n1" KeyHandler       
GameLoop         "1" *-[#595959,plain]-> "controller\n1" GameController   
GameMap           -[#595959,dashed]->  MapLayer         : "«create»"
GameMap          "1" *-[#595959,plain]-> "graphicLayers\n*" MapLayer         
GameModel        "1" *-[#595959,plain]-> "collisionChecker\n1" CollisionChecker 
GameModel         -[#595959,dashed]->  CollisionChecker : "«create»"
GameModel         -[#595959,dashed]->  Entity           
GameModel        "1" *-[#595959,plain]-> "worldGameMap\n1" GameMap          
GameModel         -[#595959,dashed]->  GameMap          : "«create»"
GameModel         -[#595959,dashed]->  KeyHandler       
GameModel        "1" *-[#595959,plain]-> "player\n1" Player           
GameModel         -[#595959,dashed]->  Player           : "«create»"
GameView         "1" *-[#595959,plain]-> "model\n1" GameModel        
GameView         "1" *-[#595959,plain]-> "mapRender\n1" MapRender        
GameView          -[#595959,dashed]->  MapRender        : "«create»"
GameView         "1" *-[#595959,plain]-> "playerRender\n1" PlayerRender     
GameView          -[#595959,dashed]->  PlayerRender     : "«create»"
GameView         "1" *-[#595959,plain]-> "tileSet\n1" TileSet          
GameView          -[#595959,dashed]->  TileSet          : "«create»"
GameView         "1" *-[#595959,plain]-> "ui_render\n1" UI               
GameView          -[#595959,dashed]->  UI               : "«create»"
Main              -[#595959,dashed]->  GameController   : "«create»"
Main              -[#595959,dashed]->  GameModel        : "«create»"
Main              -[#595959,dashed]->  GameView         : "«create»"
MapRender         -[#595959,dashed]->  Entity           
MapRender         -[#595959,dashed]->  GameMap          
MapRender         -[#595959,dashed]->  Player           
MapRender         -[#595959,dashed]->  TileSet          
OBJ_Tree          -[#000082,plain]-^  GameObject       
Player            -[#000082,plain]-^  Entity           
Player            -[#595959,dashed]->  KeyHandler       
PlayerRender      -[#595959,dashed]->  Animation        : "«create»"
PlayerRender      -[#595959,dashed]->  AnimationManager : "«create»"
PlayerRender     "1" *-[#595959,plain]-> "animationManager\n1" AnimationManager 
PlayerRender      -[#595959,dashed]->  Entity           
PlayerRender      -[#595959,dashed]->  Player           
PlayerRender      -[#595959,dashed]->  SpriteLoader     
TileSet          "1" *-[#595959,plain]-> "animatedTiles\n*" AnimatedTile     
TileSet           -[#595959,dashed]->  AnimatedTile     : "«create»"
TileSet           -[#595959,dashed]->  TileRegion       : "«create»"
TileSet          "1" *-[#595959,plain]-> "tiles\n*" TileRegion       
UI               "1" *-[#595959,plain]-> "gameModel\n1" GameModel        
UI               "1" *-[#595959,plain]-> "mapRender\n1" MapRender        
UI               "1" *-[#595959,plain]-> "playerRender\n1" PlayerRender     
@enduml
